### ISSUE TITLE
Algunas elementos de la lista del grupo staff se muestran desalineados en vista de navegador de escritorio

### ISSUE THREAD

**Issue by oevl** [pythonpanama/meetups#4]
![image](https://user-images.githubusercontent.com/174772/70279693-fadb0100-1784-11ea-959c-4896a3bbedf3.png)

**Comment by oevl** [comment]
Cambiando el tamaño de las imágenes a 550x550 hace que los elementos se muestren alineados:
![image](https://user-images.githubusercontent.com/174772/70279743-11815800-1785-11ea-8102-613084bb3e27.png)

Cambiar el sufijo de todas las imágenes en directorio img/staff a "jpg"

Cambiar el nombre de las imágenes con prefijo correjido a jpg en el documento index.html

Con ImageMagick en el directorio img/staff:
```
mogrify -resize 550x550! *.jpg
```

**Comment by adriaanbd** [comment]
Este issue ha sido solucionado por Omar en #6
